postgres_pgadmin:
  target: sandbox
  outputs:
    sandbox:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5432
      dbname: sandbox 
      schema: public
      threads: 1
      connect_timeout: 30